In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)        #create an array 0 to 10

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr1 = np .arange(0,11,3)

In [6]:
arr1

array([0, 3, 6, 9])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
arr[0:3] = 100

In [11]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

# reset the array

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

# this is not a copy of the array. its like a mirror. REASON is memorry issues for large arrays
## if you want to make a copy , u should copy it

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#       COPY() method

In [21]:
arr_copy = arr.copy()

In [22]:
arr_copy[1:7] = 888

In [23]:
arr_copy

array([ 99, 888, 888, 888, 888, 888, 888,   7,   8,   9,  10])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# 2-D arrays

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

5

In [29]:
arr_2d[1]

array([20, 25, 30])

In [30]:
arr_2d[0,0]

5

In [31]:
arr_2d[:3,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [32]:
arr_2d[:3,1]

array([10, 25, 40])

In [33]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr = np.arange(0,11)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr > 5

In [39]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr>7]

array([ 8,  9, 10])

In [44]:
arr_2d[arr_2d > 10]

array([15, 20, 25, 30, 35, 40, 45])

In [45]:
arr2 = np.arange(50).reshape(5,10)

In [46]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
arr2[:2,3:]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19]])

In [49]:
arr2[3:6,3:6]

array([[33, 34, 35],
       [43, 44, 45]])

In [55]:
ex= np.arange(0,100).reshape(5,20)

In [56]:
ex

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [59]:
ex1 = ex[1:3,0:6].copy()

In [67]:
ex1

array([[20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

In [70]:
ex1[1,1:2] = 100

In [71]:
ex1

array([[ 20,  21,  22,  23,  24,  25],
       [ 40, 100,  42,  43,  44,  45]])

In [72]:
ex1[1][2] = 200

In [73]:
ex1

array([[ 20,  21,  22,  23,  24,  25],
       [ 40, 100, 200,  43,  44,  45]])

In [74]:
ex2 = np.arange(0,1000,11)

In [75]:
ex2

array([  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132,
       143, 154, 165, 176, 187, 198, 209, 220, 231, 242, 253, 264, 275,
       286, 297, 308, 319, 330, 341, 352, 363, 374, 385, 396, 407, 418,
       429, 440, 451, 462, 473, 484, 495, 506, 517, 528, 539, 550, 561,
       572, 583, 594, 605, 616, 627, 638, 649, 660, 671, 682, 693, 704,
       715, 726, 737, 748, 759, 770, 781, 792, 803, 814, 825, 836, 847,
       858, 869, 880, 891, 902, 913, 924, 935, 946, 957, 968, 979, 990])

In [78]:
arr3 = np.arange(0,25).reshape(5,5)

In [85]:
arr3 % 3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]])

In [86]:
arr3[arr3 % 3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])