In [6]:
my_list = [1,2,3]

In [7]:
import numpy as np

In [9]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

# 2 dim arr

In [12]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange(begin, end) function 
### returns an array between range

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
mult_arr = np.zeros((5,5))

In [24]:
mult_arr[4][4] = 9

In [25]:
mult_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 9.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# the ex below shows 10 evenly sliced array between 0 to 5

In [28]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [30]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.47738436, 0.54829193, 0.54289951, 0.31797688, 0.57128822])

In [35]:
np.random.rand(5,5)

array([[0.30051318, 0.10686002, 0.3720602 , 0.45938718, 0.29539585],
       [0.82390765, 0.45146487, 0.43098839, 0.17872391, 0.87870069],
       [0.07797813, 0.840899  , 0.54103991, 0.49837154, 0.039113  ],
       [0.23129876, 0.33783103, 0.10195097, 0.12660213, 0.70712349],
       [0.86550345, 0.15068399, 0.71434959, 0.64636245, 0.18292633]])

In [36]:
np.random.randn(5,5)

array([[-0.32577572, -2.32513567,  0.86170632, -1.52409966, -0.38395354],
       [ 0.23002645, -0.76493973,  0.13664347, -0.31582716, -0.1744185 ],
       [ 0.7036566 , -0.99171816,  0.50366707,  1.16019007,  0.22797384],
       [ 0.41662507,  2.39909367, -1.82065975, -0.28497446, -1.14743068],
       [-0.18601626,  0.586113  ,  0.166654  ,  0.17251387, -2.07610589]])

In [48]:
np.random.randint(1,100,10)

array([23, 35, 23, 14, 36, 53, 55, 87, 70,  7])

In [49]:
np.random.randint(1,100)

69

In [50]:
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
ranarr = np.random.randint(0,50,10)

In [65]:
ranarr

array([ 0, 28, 10,  7, 29, 18, 48, 47, 33, 20])

In [66]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
ranarr.reshape(5,2)

array([[ 0, 28],
       [10,  7],
       [29, 18],
       [48, 47],
       [33, 20]])

In [68]:
ranarr.max()

48

In [69]:
ranarr.min()

0

In [70]:
ranarr.mean()

24.0

# argmax()    returns the index location of max

In [72]:
arr.shape

(25,)

In [73]:
arr.dtype

dtype('int64')